BEGIN
    EXECUTE IMMEDIATE 'CREATE USER WINTHOR IDENTIFIED BY Winthor123';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN
            RAISE;
        END IF;
END;
/

ALTER USER WINTHOR DEFAULT TABLESPACE users;
ALTER USER WINTHOR TEMPORARY TABLESPACE temp;
ALTER USER WINTHOR QUOTA UNLIMITED ON users;

BEGIN
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO WINTHOR';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1927, -1031) THEN
            RAISE;
        END IF;
END;
/
