CREATE INDEX IDX_PCPEDC_DATA ON WINTHOR.PCPEDC(DATA);
CREATE INDEX IDX_PCPEDC_CODCLI ON WINTHOR.PCPEDC(CODCLI);
CREATE INDEX IDX_PCPEDC_CODUSUR ON WINTHOR.PCPEDC(CODUSUR);
CREATE INDEX IDX_PCPEDC_POSICAO ON WINTHOR.PCPEDC(POSICAO);
CREATE INDEX IDX_PCPEDC_CODFILIAL ON WINTHOR.PCPEDC(CODFILIAL);

CREATE INDEX IDX_PCPEDI_NUMPED ON WINTHOR.PCPEDI(NUMPED);
CREATE INDEX IDX_PCPEDI_CODPROD ON WINTHOR.PCPEDI(CODPROD);

CREATE INDEX IDX_PCPRODUT_CODEPTO ON WINTHOR.PCPRODUT(CODEPTO);
CREATE INDEX IDX_PCPRODUT_CODSEC ON WINTHOR.PCPRODUT(CODSEC);

CREATE INDEX IDX_PCEST_CODPROD ON WINTHOR.PCEST(CODPROD);
CREATE INDEX IDX_PCEST_CODFILIAL ON WINTHOR.PCEST(CODFILIAL);

-- Índices compostos
CREATE INDEX IDX_PCPEDC_CLI_DATA ON WINTHOR.PCPEDC(CODCLI, DATA);
CREATE INDEX IDX_PCPEDC_USU_DATA ON WINTHOR.PCPEDC(CODUSUR, DATA);
CREATE INDEX IDX_PCPEDC_FIL_POS ON WINTHOR.PCPEDC(CODFILIAL, POSICAO);
