CREATE TABLE WINTHOR.PCLINHAPROD (
	CODLINHA NUMBER(6,0),
	DESCRICAO VARCHAR2(40),
	CODFILIAL VARCHAR2(2),
	NUMDIASTRABSEMANA NUMBER(4,0),
	NUMTURNODIA NUMBER(4,0),
	HORASPORTURNO NUMBER(4,0),
	NUMPESSOASTURNO NUMBER(4,0),
	CODLINHAPROD NUMBER(6,0),
	PRAZOMAXIMO NUMBER(4,0),
	OBS VARCHAR2(100)
);