CREATE TABLE WINTHOR.PCSUGESTAOCOMPRAC (
	NUMSUGESTAO NUMBER(10,0),
	CODFORNEC NUMBER(6,0),
	CODFILIAL VARCHAR2(2),
	CODUSUARIOSUGESTAO NUMBER(8,0),
	DATASUGESTAO DATE,
	CODEDITAL NUMBER(9,0),
	TIPODESCARGA VARCHAR2(1),
	IMPORTACAO VARCHAR2(1),
	TIPOEMBALAGEMPEDIDO VARCHAR2(1),
	DTPREVENT DATE
);