CREATE TABLE WINTHOR.PCCATEGORIA (
	CODSEC NUMBER(6,0),
	CODCATEGORIA NUMBER(6,0),
	CATEGORIA VARCHAR2(40),
	IDINTEGRACAOCIASHOP VARCHAR2(250),
	ENVIAECOMMERCE VARCHAR2(1) DEFAULT 'N',
	CODCATEGORIAMIGRACAO NUMBER(6,0),
	DTULTALTER DATE,
	DTCADASTRO DATE
);