BEGIN
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO WINTHOR';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1918 THEN
            RAISE_APPLICATION_ERROR(-20001, 'usuario WINTHOR nao existe para receber CREATE SESSION');
        ELSIF SQLCODE != -1927 THEN
            RAISE;
        END IF;
END;
/
