CREATE TABLE WINTHOR.PCMARCA (
	CODMARCA NUMBER(8,0),
	MARCA VARCHAR2(40),
	ATIVO VARCHAR2(1) DEFAULT 'S',
	CODMARCAMIGRACAO NUMBER(8,0),
	CODADWORDS VARCHAR2(200),
	DESCRICAOECOMMERCE VARCHAR2(400),
	CODCAMPLOMADEE VARCHAR2(200),
	TITULO VARCHAR2(200),
	DTULTALTER DATE,
	DTCADASTRO DATE,
	CODCOMPRADOR NUMBER(8,0),
	DTALTERC5 TIMESTAMP
);