CREATE TABLE WINTHOR.PCPRODSIMIL (
	CODPROD NUMBER(6,0),
	CODSIMIL NUMBER(6,0),
	CODFUNCLANC NUMBER(8,0),
	DTLANC DATE,
	TIPOPROD VARCHAR2(1),
	PRIORIDADE NUMBER(4,0),
	TIPOTROCA VARCHAR2(1),
	OBSERVACAO VARCHAR2(2000)
);