ALTER TABLE WINTHOR.PCPEDI ADD CONSTRAINT FK_PCPEDI_PCPEDC 
FOREIGN KEY (NUMPED) REFERENCES WINTHOR.PCPEDC(NUMPED);

-- PCPEDI → PCPRODUT
ALTER TABLE WINTHOR.PCPEDI ADD CONSTRAINT FK_PCPEDI_PCPRODUT 
FOREIGN KEY (CODPROD) REFERENCES WINTHOR.PCPRODUT(CODPROD);

-- PCPEDC → PCCLIENT
ALTER TABLE WINTHOR.PCPEDC ADD CONSTRAINT FK_PCPEDC_PCCLIENT 
FOREIGN KEY (CODCLI) REFERENCES WINTHOR.PCCLIENT(CODCLI);

-- PCPEDC → PCUSUARI
ALTER TABLE WINTHOR.PCPEDC ADD CONSTRAINT FK_PCPEDC_PCUSUARI 
FOREIGN KEY (CODUSUR) REFERENCES WINTHOR.PCUSUARI(CODUSUR);

-- PCPRODUT → PCDEPTO
ALTER TABLE WINTHOR.PCPRODUT ADD CONSTRAINT FK_PCPRODUT_PCDEPTO 
FOREIGN KEY (CODEPTO) REFERENCES WINTHOR.PCDEPTO(CODEPTO);

-- PCPRODUT → PCSECAO
ALTER TABLE WINTHOR.PCPRODUT ADD CONSTRAINT FK_PCPRODUT_PCSECAO 
FOREIGN KEY (CODSEC) REFERENCES WINTHOR.PCSECAO(CODSEC);

-- PCEST → PCPRODUT
ALTER TABLE WINTHOR.PCEST ADD CONSTRAINT FK_PCEST_PCPRODUT 
FOREIGN KEY (CODPROD) REFERENCES WINTHOR.PCPRODUT(CODPROD);
