MERGE INTO WINTHOR.PCDEPTO t
USING (SELECT 10 AS CODEPTO, 'Mercearia' AS DESCRICAO FROM dual) s
ON (t.CODEPTO = s.CODEPTO)
WHEN MATCHED THEN UPDATE SET t.DESCRICAO = s.DESCRICAO
WHEN NOT MATCHED THEN
  INSERT (CODEPTO, DESCRICAO)
  VALUES (s.CODEPTO, s.DESCRICAO);

MERGE INTO WINTHOR.PCSECAO t
USING (SELECT 100 AS CODSEC, 'Alimentos Basicos' AS DESCRICAO FROM dual) s
ON (t.CODSEC = s.CODSEC)
WHEN MATCHED THEN UPDATE SET t.DESCRICAO = s.DESCRICAO
WHEN NOT MATCHED THEN
  INSERT (CODSEC, DESCRICAO)
  VALUES (s.CODSEC, s.DESCRICAO);

MERGE INTO WINTHOR.PCUSUARI t
USING (
  SELECT
    1 AS CODUSUR,
    'Usuario Seed' AS NOME,
    'S' AS ATIVO,
    'seed@winthor.local' AS EMAIL
  FROM dual
) s
ON (t.CODUSUR = s.CODUSUR)
WHEN MATCHED THEN UPDATE SET
  t.NOME = s.NOME,
  t.ATIVO = s.ATIVO,
  t.EMAIL = s.EMAIL
WHEN NOT MATCHED THEN
  INSERT (CODUSUR, NOME, ATIVO, EMAIL)
  VALUES (s.CODUSUR, s.NOME, s.ATIVO, s.EMAIL);

MERGE INTO WINTHOR.PCCLIENT t
USING (
  SELECT
    1 AS CODCLI,
    'Cliente Seed LTDA' AS CLIENTE,
    '12345678000199' AS CGC,
    'Rua das Seeds, 100' AS ENDERECO,
    'Centro' AS BAIRRO,
    'Sao Paulo' AS CIDADE,
    'SP' AS ESTADO,
    '01000-000' AS CEP
  FROM dual
) s
ON (t.CODCLI = s.CODCLI)
WHEN MATCHED THEN UPDATE SET
  t.CLIENTE = s.CLIENTE,
  t.CGC = s.CGC,
  t.ENDERECO = s.ENDERECO,
  t.BAIRRO = s.BAIRRO,
  t.CIDADE = s.CIDADE,
  t.ESTADO = s.ESTADO,
  t.CEP = s.CEP
WHEN NOT MATCHED THEN
  INSERT (CODCLI, CLIENTE, CGC, ENDERECO, BAIRRO, CIDADE, ESTADO, CEP)
  VALUES (s.CODCLI, s.CLIENTE, s.CGC, s.ENDERECO, s.BAIRRO, s.CIDADE, s.ESTADO, s.CEP);

MERGE INTO WINTHOR.PCFORNEC t
USING (
  SELECT
    1 AS CODFORNEC,
    'Fornecedor Seed SA' AS FORNECEDOR,
    'Contato Compras' AS CONTATO,
    'Avenida do Fornecedor, 50' AS ENDER,
    'Campinas' AS CIDADE,
    'SP' AS ESTADO,
    '13000-000' AS CEP,
    '11999999999' AS TELFAB,
    '99888777000155' AS CGC,
    'S' AS BLOQUEIO,
    DATE '2026-04-20' AS DTCADASTRO,
    'Fornecedor base do ambiente mockado' AS OBSERVACAO,
    'compras@fornecedor.local' AS EMAIL,
    'Fornecedor Seed' AS FANTASIA,
    'C' AS TIPOFORNEC
  FROM dual
) s
ON (t.CODFORNEC = s.CODFORNEC)
WHEN MATCHED THEN UPDATE SET
  t.FORNECEDOR = s.FORNECEDOR,
  t.CONTATO = s.CONTATO,
  t.ENDER = s.ENDER,
  t.CIDADE = s.CIDADE,
  t.ESTADO = s.ESTADO,
  t.CEP = s.CEP,
  t.TELFAB = s.TELFAB,
  t.CGC = s.CGC,
  t.BLOQUEIO = s.BLOQUEIO,
  t.DTCADASTRO = s.DTCADASTRO,
  t.OBSERVACAO = s.OBSERVACAO,
  t.EMAIL = s.EMAIL,
  t.FANTASIA = s.FANTASIA,
  t.TIPOFORNEC = s.TIPOFORNEC
WHEN NOT MATCHED THEN
  INSERT (
    CODFORNEC, FORNECEDOR, CONTATO, ENDER, CIDADE, ESTADO, CEP, TELFAB, CGC,
    BLOQUEIO, DTCADASTRO, OBSERVACAO, EMAIL, FANTASIA, TIPOFORNEC
  )
  VALUES (
    s.CODFORNEC, s.FORNECEDOR, s.CONTATO, s.ENDER, s.CIDADE, s.ESTADO, s.CEP, s.TELFAB, s.CGC,
    s.BLOQUEIO, s.DTCADASTRO, s.OBSERVACAO, s.EMAIL, s.FANTASIA, s.TIPOFORNEC
  );

MERGE INTO WINTHOR.PCFILIAL t
USING (
  SELECT
    '01' AS CODIGO,
    'Filial Seed Matriz' AS RAZAOSOCIAL,
    'Rua da Matriz, 1' AS ENDERECO,
    'Sao Paulo' AS CIDADE,
    'SP' AS UF,
    '01000000' AS CEP,
    '1133334444' AS TELEFONE,
    '11222333000144' AS CGC,
    1 AS CODCLI,
    1 AS CODFORNEC,
    1000 AS PROXNUMNOTA,
    5000 AS NUMPROXVEND,
    'N' AS INDUSTRIA,
    'Filial Seed' AS FANTASIA,
    999 AS CODCLICONSUMIDOR
  FROM dual
) s
ON (t.CODIGO = s.CODIGO)
WHEN MATCHED THEN UPDATE SET
  t.RAZAOSOCIAL = s.RAZAOSOCIAL,
  t.ENDERECO = s.ENDERECO,
  t.CIDADE = s.CIDADE,
  t.UF = s.UF,
  t.CEP = s.CEP,
  t.TELEFONE = s.TELEFONE,
  t.CGC = s.CGC,
  t.CODCLI = s.CODCLI,
  t.CODFORNEC = s.CODFORNEC,
  t.PROXNUMNOTA = s.PROXNUMNOTA,
  t.NUMPROXVEND = s.NUMPROXVEND,
  t.INDUSTRIA = s.INDUSTRIA,
  t.FANTASIA = s.FANTASIA,
  t.CODCLICONSUMIDOR = s.CODCLICONSUMIDOR
WHEN NOT MATCHED THEN
  INSERT (
    CODIGO, RAZAOSOCIAL, ENDERECO, CIDADE, UF, CEP, TELEFONE, CGC,
    CODCLI, CODFORNEC, PROXNUMNOTA, NUMPROXVEND, INDUSTRIA, FANTASIA, CODCLICONSUMIDOR
  )
  VALUES (
    s.CODIGO, s.RAZAOSOCIAL, s.ENDERECO, s.CIDADE, s.UF, s.CEP, s.TELEFONE, s.CGC,
    s.CODCLI, s.CODFORNEC, s.PROXNUMNOTA, s.NUMPROXVEND, s.INDUSTRIA, s.FANTASIA, s.CODCLICONSUMIDOR
  );

MERGE INTO WINTHOR.PCCOB t
USING (
  SELECT
    '001' AS CODCOB,
    'Boleto Bancario' AS COBRANCA,
    'S' AS PAGCOMISSAO,
    2.50 AS TXJUROS,
    30 AS PRAZOMAXIMOVENDA,
    'BL' AS LETRACOB,
    'N' AS BOLETO,
    'S' AS ENVIACOBRANCAFV
  FROM dual
) s
ON (t.CODCOB = s.CODCOB)
WHEN MATCHED THEN UPDATE SET
  t.COBRANCA = s.COBRANCA,
  t.PAGCOMISSAO = s.PAGCOMISSAO,
  t.TXJUROS = s.TXJUROS,
  t.PRAZOMAXIMOVENDA = s.PRAZOMAXIMOVENDA,
  t.LETRACOB = s.LETRACOB,
  t.BOLETO = s.BOLETO,
  t.ENVIACOBRANCAFV = s.ENVIACOBRANCAFV
WHEN NOT MATCHED THEN
  INSERT (CODCOB, COBRANCA, PAGCOMISSAO, TXJUROS, PRAZOMAXIMOVENDA, LETRACOB, BOLETO, ENVIACOBRANCAFV)
  VALUES (s.CODCOB, s.COBRANCA, s.PAGCOMISSAO, s.TXJUROS, s.PRAZOMAXIMOVENDA, s.LETRACOB, s.BOLETO, s.ENVIACOBRANCAFV);

MERGE INTO WINTHOR.PCPLPAG t
USING (
  SELECT
    1 AS CODPLPAG,
    '28 DIAS' AS DESCRICAO,
    28 AS NUMDIAS,
    'P' AS TIPOPRAZO,
    28 AS PRAZO1,
    'VD' AS TIPOVENDA,
    'N' AS OFERTA,
    'S' AS VENDABK,
    '001' AS CODCOB,
    'S' AS STATUS
  FROM dual
) s
ON (t.CODPLPAG = s.CODPLPAG)
WHEN MATCHED THEN UPDATE SET
  t.DESCRICAO = s.DESCRICAO,
  t.NUMDIAS = s.NUMDIAS,
  t.TIPOPRAZO = s.TIPOPRAZO,
  t.PRAZO1 = s.PRAZO1,
  t.TIPOVENDA = s.TIPOVENDA,
  t.OFERTA = s.OFERTA,
  t.VENDABK = s.VENDABK,
  t.CODCOB = s.CODCOB,
  t.STATUS = s.STATUS
WHEN NOT MATCHED THEN
  INSERT (CODPLPAG, DESCRICAO, NUMDIAS, TIPOPRAZO, PRAZO1, TIPOVENDA, OFERTA, VENDABK, CODCOB, STATUS)
  VALUES (s.CODPLPAG, s.DESCRICAO, s.NUMDIAS, s.TIPOPRAZO, s.PRAZO1, s.TIPOVENDA, s.OFERTA, s.VENDABK, s.CODCOB, s.STATUS);

MERGE INTO WINTHOR.PCCONSUM t
USING (
  SELECT
    '44555666000177' AS CGC,
    'Mock Distribuidora' AS EMPRESA,
    'Avenida Principal, 10' AS ENDERECO,
    'Sao Paulo' AS CIDADE,
    'SP' AS ESTADO,
    '01000000' AS CEP,
    25000 AS PROXNUMPED,
    5000 AS PROXNUMCLI,
    3000 AS PROXNUMFORNEC,
    6000 AS PROXNUMPRODUT,
    40000 AS PROXNUMTRANS,
    50000 AS PROXNUMTRANSENT,
    0.050000 AS TXVENDA
  FROM dual
) s
ON (t.CGC = s.CGC)
WHEN MATCHED THEN UPDATE SET
  t.EMPRESA = s.EMPRESA,
  t.ENDERECO = s.ENDERECO,
  t.CIDADE = s.CIDADE,
  t.ESTADO = s.ESTADO,
  t.CEP = s.CEP,
  t.PROXNUMPED = s.PROXNUMPED,
  t.PROXNUMCLI = s.PROXNUMCLI,
  t.PROXNUMFORNEC = s.PROXNUMFORNEC,
  t.PROXNUMPRODUT = s.PROXNUMPRODUT,
  t.PROXNUMTRANS = s.PROXNUMTRANS,
  t.PROXNUMTRANSENT = s.PROXNUMTRANSENT,
  t.TXVENDA = s.TXVENDA
WHEN NOT MATCHED THEN
  INSERT (
    CGC, EMPRESA, ENDERECO, CIDADE, ESTADO, CEP,
    PROXNUMPED, PROXNUMCLI, PROXNUMFORNEC, PROXNUMPRODUT, PROXNUMTRANS, PROXNUMTRANSENT, TXVENDA
  )
  VALUES (
    s.CGC, s.EMPRESA, s.ENDERECO, s.CIDADE, s.ESTADO, s.CEP,
    s.PROXNUMPED, s.PROXNUMCLI, s.PROXNUMFORNEC, s.PROXNUMPRODUT, s.PROXNUMTRANS, s.PROXNUMTRANSENT, s.TXVENDA
  );

MERGE INTO WINTHOR.PCMARCA t
USING (
  SELECT 1 AS CODMARCA, 'Marca Seed' AS MARCA, 'S' AS ATIVO, DATE '2026-04-20' AS DTCADASTRO FROM dual
) s
ON (t.CODMARCA = s.CODMARCA)
WHEN MATCHED THEN UPDATE SET
  t.MARCA = s.MARCA,
  t.ATIVO = s.ATIVO,
  t.DTCADASTRO = s.DTCADASTRO
WHEN NOT MATCHED THEN
  INSERT (CODMARCA, MARCA, ATIVO, DTCADASTRO)
  VALUES (s.CODMARCA, s.MARCA, s.ATIVO, s.DTCADASTRO);

MERGE INTO WINTHOR.PCCATEGORIA t
USING (
  SELECT 100 AS CODSEC, 1 AS CODCATEGORIA, 'Secos e Graos' AS CATEGORIA, 'N' AS ENVIAECOMMERCE, DATE '2026-04-20' AS DTCADASTRO FROM dual
) s
ON (t.CODSEC = s.CODSEC AND t.CODCATEGORIA = s.CODCATEGORIA)
WHEN MATCHED THEN UPDATE SET
  t.CATEGORIA = s.CATEGORIA,
  t.ENVIAECOMMERCE = s.ENVIAECOMMERCE,
  t.DTCADASTRO = s.DTCADASTRO
WHEN NOT MATCHED THEN
  INSERT (CODSEC, CODCATEGORIA, CATEGORIA, ENVIAECOMMERCE, DTCADASTRO)
  VALUES (s.CODSEC, s.CODCATEGORIA, s.CATEGORIA, s.ENVIAECOMMERCE, s.DTCADASTRO);

MERGE INTO WINTHOR.PCLINHAPROD t
USING (
  SELECT 1 AS CODLINHA, 'Linha Padrao' AS DESCRICAO, '01' AS CODFILIAL, 5 AS NUMDIASTRABSEMANA, 2 AS NUMTURNODIA, 8 AS HORASPORTURNO FROM dual
) s
ON (t.CODLINHA = s.CODLINHA)
WHEN MATCHED THEN UPDATE SET
  t.DESCRICAO = s.DESCRICAO,
  t.CODFILIAL = s.CODFILIAL,
  t.NUMDIASTRABSEMANA = s.NUMDIASTRABSEMANA,
  t.NUMTURNODIA = s.NUMTURNODIA,
  t.HORASPORTURNO = s.HORASPORTURNO
WHEN NOT MATCHED THEN
  INSERT (CODLINHA, DESCRICAO, CODFILIAL, NUMDIASTRABSEMANA, NUMTURNODIA, HORASPORTURNO)
  VALUES (s.CODLINHA, s.DESCRICAO, s.CODFILIAL, s.NUMDIASTRABSEMANA, s.NUMTURNODIA, s.HORASPORTURNO);

MERGE INTO WINTHOR.PCROTULOITEM t
USING (
  SELECT 'ROT-001' AS ID, 'Rotulo base do produto seed' AS DESCRICAO, 'ATIVO' AS VALOR, DATE '2026-04-20' AS DTCADASTRO, 'N' AS CRIADOPELOCLIENTE FROM dual
) s
ON (t.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
  t.DESCRICAO = s.DESCRICAO,
  t.VALOR = s.VALOR,
  t.DTCADASTRO = s.DTCADASTRO,
  t.CRIADOPELOCLIENTE = s.CRIADOPELOCLIENTE
WHEN NOT MATCHED THEN
  INSERT (ID, DESCRICAO, VALOR, DTCADASTRO, CRIADOPELOCLIENTE)
  VALUES (s.ID, s.DESCRICAO, s.VALOR, s.DTCADASTRO, s.CRIADOPELOCLIENTE);

MERGE INTO WINTHOR.PCPRODUT t
USING (
  SELECT
    1001 AS CODPROD,
    'ARROZ TIPO 1 5KG' AS DESCRICAO,
    10 AS CODEPTO,
    100 AS CODSEC,
    5.200 AS PESOBRUTO,
    5.000 AS PESOLIQ,
    1.000 AS QTUNITCX,
    'FD' AS EMBALAGEM,
    19.5000 AS CUSTOREP
  FROM dual
) s
ON (t.CODPROD = s.CODPROD)
WHEN MATCHED THEN UPDATE SET
  t.DESCRICAO = s.DESCRICAO,
  t.CODEPTO = s.CODEPTO,
  t.CODSEC = s.CODSEC,
  t.PESOBRUTO = s.PESOBRUTO,
  t.PESOLIQ = s.PESOLIQ,
  t.QTUNITCX = s.QTUNITCX,
  t.EMBALAGEM = s.EMBALAGEM,
  t.CUSTOREP = s.CUSTOREP
WHEN NOT MATCHED THEN
  INSERT (CODPROD, DESCRICAO, CODEPTO, CODSEC, PESOBRUTO, PESOLIQ, QTUNITCX, EMBALAGEM, CUSTOREP)
  VALUES (s.CODPROD, s.DESCRICAO, s.CODEPTO, s.CODSEC, s.PESOBRUTO, s.PESOLIQ, s.QTUNITCX, s.EMBALAGEM, s.CUSTOREP);

MERGE INTO WINTHOR.PCPRODUT t
USING (
  SELECT
    1002 AS CODPROD,
    'FEIJAO CARIOCA 1KG' AS DESCRICAO,
    10 AS CODEPTO,
    100 AS CODSEC,
    1.100 AS PESOBRUTO,
    1.000 AS PESOLIQ,
    1.000 AS QTUNITCX,
    'PC' AS EMBALAGEM,
    7.3500 AS CUSTOREP
  FROM dual
) s
ON (t.CODPROD = s.CODPROD)
WHEN MATCHED THEN UPDATE SET
  t.DESCRICAO = s.DESCRICAO,
  t.CODEPTO = s.CODEPTO,
  t.CODSEC = s.CODSEC,
  t.PESOBRUTO = s.PESOBRUTO,
  t.PESOLIQ = s.PESOLIQ,
  t.QTUNITCX = s.QTUNITCX,
  t.EMBALAGEM = s.EMBALAGEM,
  t.CUSTOREP = s.CUSTOREP
WHEN NOT MATCHED THEN
  INSERT (CODPROD, DESCRICAO, CODEPTO, CODSEC, PESOBRUTO, PESOLIQ, QTUNITCX, EMBALAGEM, CUSTOREP)
  VALUES (s.CODPROD, s.DESCRICAO, s.CODEPTO, s.CODSEC, s.PESOBRUTO, s.PESOLIQ, s.QTUNITCX, s.EMBALAGEM, s.CUSTOREP);

MERGE INTO WINTHOR.PCEMBALAGEM t
USING (
  SELECT
    7891000000001 AS CODAUXILIAR,
    1001 AS CODPROD,
    'FD' AS EMBALAGEM,
    'UN' AS UNIDADE,
    1.000000 AS QTUNIT,
    24.900 AS PTABELA,
    23.900 AS PVENDA,
    '01' AS CODFILIAL,
    'S' AS EXCLUIDO
  FROM dual
) s
ON (t.CODAUXILIAR = s.CODAUXILIAR AND t.CODPROD = s.CODPROD)
WHEN MATCHED THEN UPDATE SET
  t.EMBALAGEM = s.EMBALAGEM,
  t.UNIDADE = s.UNIDADE,
  t.QTUNIT = s.QTUNIT,
  t.PTABELA = s.PTABELA,
  t.PVENDA = s.PVENDA,
  t.CODFILIAL = s.CODFILIAL,
  t.EXCLUIDO = s.EXCLUIDO
WHEN NOT MATCHED THEN
  INSERT (CODAUXILIAR, CODPROD, EMBALAGEM, UNIDADE, QTUNIT, PTABELA, PVENDA, CODFILIAL, EXCLUIDO)
  VALUES (s.CODAUXILIAR, s.CODPROD, s.EMBALAGEM, s.UNIDADE, s.QTUNIT, s.PTABELA, s.PVENDA, s.CODFILIAL, s.EXCLUIDO);

MERGE INTO WINTHOR.PCEST t
USING (
  SELECT 1001 AS CODPROD, '01' AS CODFILIAL, 120.000 AS QTESTGER, 15.000 AS QTRESERV, 0.000 AS QTBLOQUEADA FROM dual
) s
ON (t.CODPROD = s.CODPROD AND t.CODFILIAL = s.CODFILIAL)
WHEN MATCHED THEN UPDATE SET
  t.QTESTGER = s.QTESTGER,
  t.QTRESERV = s.QTRESERV,
  t.QTBLOQUEADA = s.QTBLOQUEADA
WHEN NOT MATCHED THEN
  INSERT (CODPROD, CODFILIAL, QTESTGER, QTRESERV, QTBLOQUEADA)
  VALUES (s.CODPROD, s.CODFILIAL, s.QTESTGER, s.QTRESERV, s.QTBLOQUEADA);

MERGE INTO WINTHOR.PCEST t
USING (
  SELECT 1002 AS CODPROD, '01' AS CODFILIAL, 80.000 AS QTESTGER, 8.000 AS QTRESERV, 2.000 AS QTBLOQUEADA FROM dual
) s
ON (t.CODPROD = s.CODPROD AND t.CODFILIAL = s.CODFILIAL)
WHEN MATCHED THEN UPDATE SET
  t.QTESTGER = s.QTESTGER,
  t.QTRESERV = s.QTRESERV,
  t.QTBLOQUEADA = s.QTBLOQUEADA
WHEN NOT MATCHED THEN
  INSERT (CODPROD, CODFILIAL, QTESTGER, QTRESERV, QTBLOQUEADA)
  VALUES (s.CODPROD, s.CODFILIAL, s.QTESTGER, s.QTRESERV, s.QTBLOQUEADA);

MERGE INTO WINTHOR.PCTABPR t
USING (
  SELECT 1001 AS CODPROD, 1 AS NUMREGIAO, 24.900000 AS PTABELA, 23.900000 AS PVENDA, 5.00 AS PERDESCMAX, 18.00 AS MARGEM, 'N' AS EXCLUIDO, DATE '2026-04-20' AS DTULTALTPVENDA FROM dual
) s
ON (t.CODPROD = s.CODPROD AND t.NUMREGIAO = s.NUMREGIAO)
WHEN MATCHED THEN UPDATE SET
  t.PTABELA = s.PTABELA,
  t.PVENDA = s.PVENDA,
  t.PERDESCMAX = s.PERDESCMAX,
  t.MARGEM = s.MARGEM,
  t.EXCLUIDO = s.EXCLUIDO,
  t.DTULTALTPVENDA = s.DTULTALTPVENDA
WHEN NOT MATCHED THEN
  INSERT (CODPROD, NUMREGIAO, PTABELA, PVENDA, PERDESCMAX, MARGEM, EXCLUIDO, DTULTALTPVENDA)
  VALUES (s.CODPROD, s.NUMREGIAO, s.PTABELA, s.PVENDA, s.PERDESCMAX, s.MARGEM, s.EXCLUIDO, s.DTULTALTPVENDA);

MERGE INTO WINTHOR.PCTABPR t
USING (
  SELECT 1002 AS CODPROD, 1 AS NUMREGIAO, 9.900000 AS PTABELA, 8.990000 AS PVENDA, 4.00 AS PERDESCMAX, 16.00 AS MARGEM, 'N' AS EXCLUIDO, DATE '2026-04-20' AS DTULTALTPVENDA FROM dual
) s
ON (t.CODPROD = s.CODPROD AND t.NUMREGIAO = s.NUMREGIAO)
WHEN MATCHED THEN UPDATE SET
  t.PTABELA = s.PTABELA,
  t.PVENDA = s.PVENDA,
  t.PERDESCMAX = s.PERDESCMAX,
  t.MARGEM = s.MARGEM,
  t.EXCLUIDO = s.EXCLUIDO,
  t.DTULTALTPVENDA = s.DTULTALTPVENDA
WHEN NOT MATCHED THEN
  INSERT (CODPROD, NUMREGIAO, PTABELA, PVENDA, PERDESCMAX, MARGEM, EXCLUIDO, DTULTALTPVENDA)
  VALUES (s.CODPROD, s.NUMREGIAO, s.PTABELA, s.PVENDA, s.PERDESCMAX, s.MARGEM, s.EXCLUIDO, s.DTULTALTPVENDA);

MERGE INTO WINTHOR.PCPEDC t
USING (
  SELECT 5001 AS NUMPED, 1 AS CODCLI, 1 AS CODUSUR, DATE '2026-04-20' AS DATA, 'F' AS POSICAO, '01' AS CODFILIAL, 1 AS CONDVENDA, 56.88 AS VLTOTAL FROM dual
) s
ON (t.NUMPED = s.NUMPED)
WHEN MATCHED THEN UPDATE SET
  t.CODCLI = s.CODCLI,
  t.CODUSUR = s.CODUSUR,
  t.DATA = s.DATA,
  t.POSICAO = s.POSICAO,
  t.CODFILIAL = s.CODFILIAL,
  t.CONDVENDA = s.CONDVENDA,
  t.VLTOTAL = s.VLTOTAL
WHEN NOT MATCHED THEN
  INSERT (NUMPED, CODCLI, CODUSUR, DATA, POSICAO, CODFILIAL, CONDVENDA, VLTOTAL)
  VALUES (s.NUMPED, s.CODCLI, s.CODUSUR, s.DATA, s.POSICAO, s.CODFILIAL, s.CONDVENDA, s.VLTOTAL);

MERGE INTO WINTHOR.PCPEDI t
USING (
  SELECT 5001 AS NUMPED, 1 AS NUMITEM, 1001 AS CODPROD, 2.000 AS QT, 23.9000 AS PVENDA, 19.5000 AS VLCUSTOFIN, 'N' AS BONIFIC FROM dual
) s
ON (t.NUMPED = s.NUMPED AND t.NUMITEM = s.NUMITEM)
WHEN MATCHED THEN UPDATE SET
  t.CODPROD = s.CODPROD,
  t.QT = s.QT,
  t.PVENDA = s.PVENDA,
  t.VLCUSTOFIN = s.VLCUSTOFIN,
  t.BONIFIC = s.BONIFIC
WHEN NOT MATCHED THEN
  INSERT (NUMPED, NUMITEM, CODPROD, QT, PVENDA, VLCUSTOFIN, BONIFIC)
  VALUES (s.NUMPED, s.NUMITEM, s.CODPROD, s.QT, s.PVENDA, s.VLCUSTOFIN, s.BONIFIC);

MERGE INTO WINTHOR.PCPEDI t
USING (
  SELECT 5001 AS NUMPED, 2 AS NUMITEM, 1002 AS CODPROD, 1.000 AS QT, 8.9900 AS PVENDA, 7.3500 AS VLCUSTOFIN, 'N' AS BONIFIC FROM dual
) s
ON (t.NUMPED = s.NUMPED AND t.NUMITEM = s.NUMITEM)
WHEN MATCHED THEN UPDATE SET
  t.CODPROD = s.CODPROD,
  t.QT = s.QT,
  t.PVENDA = s.PVENDA,
  t.VLCUSTOFIN = s.VLCUSTOFIN,
  t.BONIFIC = s.BONIFIC
WHEN NOT MATCHED THEN
  INSERT (NUMPED, NUMITEM, CODPROD, QT, PVENDA, VLCUSTOFIN, BONIFIC)
  VALUES (s.NUMPED, s.NUMITEM, s.CODPROD, s.QT, s.PVENDA, s.VLCUSTOFIN, s.BONIFIC);

MERGE INTO WINTHOR.PCPEDIDO t
USING (
  SELECT 6001 AS NUMPED, DATE '2026-04-20' AS DTEMISSAO, 1 AS CODFORNEC, 195.00 AS VLTOTAL, DATE '2026-04-27' AS DTPREVENT, 'Pedido de compra seed' AS OBS, '01' AS CODFILIAL, 1 AS CODPLPAG, 190.00 AS VLPRODUTO, 5.00 AS VLFRETE, 'N' AS CONFIRMADO FROM dual
) s
ON (t.NUMPED = s.NUMPED)
WHEN MATCHED THEN UPDATE SET
  t.DTEMISSAO = s.DTEMISSAO,
  t.CODFORNEC = s.CODFORNEC,
  t.VLTOTAL = s.VLTOTAL,
  t.DTPREVENT = s.DTPREVENT,
  t.OBS = s.OBS,
  t.CODFILIAL = s.CODFILIAL,
  t.CODPLPAG = s.CODPLPAG,
  t.VLPRODUTO = s.VLPRODUTO,
  t.VLFRETE = s.VLFRETE,
  t.CONFIRMADO = s.CONFIRMADO
WHEN NOT MATCHED THEN
  INSERT (NUMPED, DTEMISSAO, CODFORNEC, VLTOTAL, DTPREVENT, OBS, CODFILIAL, CODPLPAG, VLPRODUTO, VLFRETE, CONFIRMADO)
  VALUES (s.NUMPED, s.DTEMISSAO, s.CODFORNEC, s.VLTOTAL, s.DTPREVENT, s.OBS, s.CODFILIAL, s.CODPLPAG, s.VLPRODUTO, s.VLFRETE, s.CONFIRMADO);

MERGE INTO WINTHOR.PCITEM t
USING (
  SELECT 1001 AS CODPROD, 6001 AS NUMPED, 19.500000 AS PCOMPRA, 10.000000 AS QTPEDIDA, 0.000000 AS QTENTREGUE, 18.500000 AS PLIQUIDO, 5.0000 AS PERICM, 0.0000 AS PERCDESC, 10 AS NUMSEQ, DATE '2026-04-27' AS DATAENTREGA, 24.900000 AS PTABELA, 'AB' AS STATUS FROM dual
) s
ON (t.CODPROD = s.CODPROD AND t.NUMPED = s.NUMPED AND t.NUMSEQ = s.NUMSEQ)
WHEN MATCHED THEN UPDATE SET
  t.PCOMPRA = s.PCOMPRA,
  t.QTPEDIDA = s.QTPEDIDA,
  t.QTENTREGUE = s.QTENTREGUE,
  t.PLIQUIDO = s.PLIQUIDO,
  t.PERICM = s.PERICM,
  t.PERCDESC = s.PERCDESC,
  t.DATAENTREGA = s.DATAENTREGA,
  t.PTABELA = s.PTABELA,
  t.STATUS = s.STATUS
WHEN NOT MATCHED THEN
  INSERT (CODPROD, NUMPED, PCOMPRA, QTPEDIDA, QTENTREGUE, PLIQUIDO, PERICM, PERCDESC, NUMSEQ, DATAENTREGA, PTABELA, STATUS)
  VALUES (s.CODPROD, s.NUMPED, s.PCOMPRA, s.QTPEDIDA, s.QTENTREGUE, s.PLIQUIDO, s.PERICM, s.PERCDESC, s.NUMSEQ, s.DATAENTREGA, s.PTABELA, s.STATUS);

MERGE INTO WINTHOR.PCNFENT t
USING (
  SELECT 'NF' AS ESPECIE, '1' AS SERIE, 9001 AS NUMNOTA, DATE '2026-04-20' AS DTEMISSAO, DATE '2026-04-21' AS DTENT, 1 AS CODFORNEC, 195.00 AS VLTOTAL, 1102 AS CODFISCAL, '01' AS CODFILIAL, 'Nota fiscal de entrada seed' AS OBS, 10 AS NUMVOL, 52.000000 AS TOTPESO, 5.00 AS VLFRETE, 190.00 AS VLTOTGER, 'SP' AS UF, 195.00 AS VLBASE, 9.75 AS VLICMS, 0.00 AS VLOUTRAS, 'Fornecedor Seed SA' AS FORNECEDOR, '99888777000155' AS CGC, 'C' AS TIPOFORNEC FROM dual
) s
ON (t.NUMNOTA = s.NUMNOTA AND t.CODFORNEC = s.CODFORNEC AND t.SERIE = s.SERIE)
WHEN MATCHED THEN UPDATE SET
  t.ESPECIE = s.ESPECIE,
  t.DTEMISSAO = s.DTEMISSAO,
  t.DTENT = s.DTENT,
  t.VLTOTAL = s.VLTOTAL,
  t.CODFISCAL = s.CODFISCAL,
  t.CODFILIAL = s.CODFILIAL,
  t.OBS = s.OBS,
  t.NUMVOL = s.NUMVOL,
  t.TOTPESO = s.TOTPESO,
  t.VLFRETE = s.VLFRETE,
  t.VLTOTGER = s.VLTOTGER,
  t.UF = s.UF,
  t.VLBASE = s.VLBASE,
  t.VLICMS = s.VLICMS,
  t.VLOUTRAS = s.VLOUTRAS,
  t.FORNECEDOR = s.FORNECEDOR,
  t.CGC = s.CGC,
  t.TIPOFORNEC = s.TIPOFORNEC
WHEN NOT MATCHED THEN
  INSERT (
    ESPECIE, SERIE, NUMNOTA, DTEMISSAO, DTENT, CODFORNEC, VLTOTAL, CODFISCAL,
    CODFILIAL, OBS, NUMVOL, TOTPESO, VLFRETE, VLTOTGER, UF, VLBASE, VLICMS, VLOUTRAS,
    FORNECEDOR, CGC, TIPOFORNEC
  )
  VALUES (
    s.ESPECIE, s.SERIE, s.NUMNOTA, s.DTEMISSAO, s.DTENT, s.CODFORNEC, s.VLTOTAL, s.CODFISCAL,
    s.CODFILIAL, s.OBS, s.NUMVOL, s.TOTPESO, s.VLFRETE, s.VLTOTGER, s.UF, s.VLBASE, s.VLICMS, s.VLOUTRAS,
    s.FORNECEDOR, s.CGC, s.TIPOFORNEC
  );

MERGE INTO WINTHOR.PCNFENTPREENT t
USING (
  SELECT 'PE' AS ESPECIE, '1' AS SERIE, 9002 AS NUMNOTA, DATE '2026-04-20' AS DTEMISSAO, DATE '2026-04-22' AS DTENT, 1 AS CODFORNEC, 195.00 AS VLTOTAL, 1102 AS CODFISCAL, '01' AS CODFILIAL, 'Pre-entrada seed' AS OBS, 10 AS NUMVOL, 52.000000 AS TOTPESO, 5.00 AS VLFRETE, 190.00 AS VLTOTALITENS, 'AB' AS STATUS, 6001 AS NUMPEDPREENT, 'N' AS TIPOPREENT FROM dual
) s
ON (t.NUMNOTA = s.NUMNOTA AND t.CODFORNEC = s.CODFORNEC AND t.SERIE = s.SERIE)
WHEN MATCHED THEN UPDATE SET
  t.ESPECIE = s.ESPECIE,
  t.DTEMISSAO = s.DTEMISSAO,
  t.DTENT = s.DTENT,
  t.VLTOTAL = s.VLTOTAL,
  t.CODFISCAL = s.CODFISCAL,
  t.CODFILIAL = s.CODFILIAL,
  t.OBS = s.OBS,
  t.NUMVOL = s.NUMVOL,
  t.TOTPESO = s.TOTPESO,
  t.VLFRETE = s.VLFRETE,
  t.VLTOTALITENS = s.VLTOTALITENS,
  t.STATUS = s.STATUS,
  t.NUMPEDPREENT = s.NUMPEDPREENT,
  t.TIPOPREENT = s.TIPOPREENT
WHEN NOT MATCHED THEN
  INSERT (
    ESPECIE, SERIE, NUMNOTA, DTEMISSAO, DTENT, CODFORNEC, VLTOTAL, CODFISCAL,
    CODFILIAL, OBS, NUMVOL, TOTPESO, VLFRETE, VLTOTALITENS, STATUS, NUMPEDPREENT, TIPOPREENT
  )
  VALUES (
    s.ESPECIE, s.SERIE, s.NUMNOTA, s.DTEMISSAO, s.DTENT, s.CODFORNEC, s.VLTOTAL, s.CODFISCAL,
    s.CODFILIAL, s.OBS, s.NUMVOL, s.TOTPESO, s.VLFRETE, s.VLTOTALITENS, s.STATUS, s.NUMPEDPREENT, s.TIPOPREENT
  );

MERGE INTO WINTHOR.PCMOVPREENT t
USING (
  SELECT DATE '2026-04-22' AS DTMOV, 1001 AS CODPROD, 9002 AS NUMNOTA, 'EN' AS CODOPER, 10.000000 AS QT, 19.500000 AS PUNIT, '01' AS CODFILIAL, 'AB' AS STATUS, 1 AS CODUSUR, 6001 AS NUMPED, 24.900000 AS PTABELA, 10 AS CODEPTO, 100 AS CODSEC, 1 AS CODFORNEC, 1 AS CODPLPAG, 19.500000 AS CUSTOFIN, 19.500000 AS CUSTOCONT, 19.500000 AS CUSTOREAL, 19.500000 AS CUSTOREP FROM dual
) s
ON (t.NUMNOTA = s.NUMNOTA AND t.CODPROD = s.CODPROD AND t.CODOPER = s.CODOPER)
WHEN MATCHED THEN UPDATE SET
  t.DTMOV = s.DTMOV,
  t.QT = s.QT,
  t.PUNIT = s.PUNIT,
  t.CODFILIAL = s.CODFILIAL,
  t.STATUS = s.STATUS,
  t.CODUSUR = s.CODUSUR,
  t.NUMPED = s.NUMPED,
  t.PTABELA = s.PTABELA,
  t.CODEPTO = s.CODEPTO,
  t.CODSEC = s.CODSEC,
  t.CODFORNEC = s.CODFORNEC,
  t.CODPLPAG = s.CODPLPAG,
  t.CUSTOFIN = s.CUSTOFIN,
  t.CUSTOCONT = s.CUSTOCONT,
  t.CUSTOREAL = s.CUSTOREAL,
  t.CUSTOREP = s.CUSTOREP
WHEN NOT MATCHED THEN
  INSERT (
    DTMOV, CODPROD, NUMNOTA, CODOPER, QT, PUNIT, CODFILIAL, STATUS, CODUSUR, NUMPED,
    PTABELA, CODEPTO, CODSEC, CODFORNEC, CODPLPAG, CUSTOFIN, CUSTOCONT, CUSTOREAL, CUSTOREP
  )
  VALUES (
    s.DTMOV, s.CODPROD, s.NUMNOTA, s.CODOPER, s.QT, s.PUNIT, s.CODFILIAL, s.STATUS, s.CODUSUR, s.NUMPED,
    s.PTABELA, s.CODEPTO, s.CODSEC, s.CODFORNEC, s.CODPLPAG, s.CUSTOFIN, s.CUSTOCONT, s.CUSTOREAL, s.CUSTOREP
  );

MERGE INTO WINTHOR.PCNFSAID t
USING (
  SELECT 'NF' AS ESPECIE, '1' AS SERIE, 9101 AS NUMNOTA, DATE '2026-04-20' AS DTSAIDA, 56.88 AS VLTOTAL, 5102 AS CODFISCAL, 1 AS CODCLI, 1 AS CODUSUR, DATE '2026-04-21' AS DTENTREGA, 56.88 AS VLTOTGER, '01' AS CODFILIAL, 0.00 AS VLDESCONTO, 'VD' AS TIPOVENDA, 'Nota fiscal de saida seed' AS OBS, 1.00 AS TOTVOLUME, 2 AS NUMITENS, '001' AS CODCOB, 5001 AS NUMPED, 1 AS CODPLPAG, 1 AS CONDVENDA, 'SP' AS UF, 56.88 AS VLBASE, 2.84 AS VLICMS, 0.00 AS VLOUTRAS FROM dual
) s
ON (t.NUMNOTA = s.NUMNOTA AND t.CODCLI = s.CODCLI AND t.SERIE = s.SERIE)
WHEN MATCHED THEN UPDATE SET
  t.ESPECIE = s.ESPECIE,
  t.DTSAIDA = s.DTSAIDA,
  t.VLTOTAL = s.VLTOTAL,
  t.CODFISCAL = s.CODFISCAL,
  t.CODUSUR = s.CODUSUR,
  t.DTENTREGA = s.DTENTREGA,
  t.VLTOTGER = s.VLTOTGER,
  t.CODFILIAL = s.CODFILIAL,
  t.VLDESCONTO = s.VLDESCONTO,
  t.TIPOVENDA = s.TIPOVENDA,
  t.OBS = s.OBS,
  t.TOTVOLUME = s.TOTVOLUME,
  t.NUMITENS = s.NUMITENS,
  t.CODCOB = s.CODCOB,
  t.NUMPED = s.NUMPED,
  t.CODPLPAG = s.CODPLPAG,
  t.CONDVENDA = s.CONDVENDA,
  t.UF = s.UF,
  t.VLBASE = s.VLBASE,
  t.VLICMS = s.VLICMS,
  t.VLOUTRAS = s.VLOUTRAS
WHEN NOT MATCHED THEN
  INSERT (
    ESPECIE, SERIE, NUMNOTA, DTSAIDA, VLTOTAL, CODFISCAL, CODCLI, CODUSUR, DTENTREGA,
    VLTOTGER, CODFILIAL, VLDESCONTO, TIPOVENDA, OBS, TOTVOLUME, NUMITENS, CODCOB,
    NUMPED, CODPLPAG, CONDVENDA, UF, VLBASE, VLICMS, VLOUTRAS
  )
  VALUES (
    s.ESPECIE, s.SERIE, s.NUMNOTA, s.DTSAIDA, s.VLTOTAL, s.CODFISCAL, s.CODCLI, s.CODUSUR, s.DTENTREGA,
    s.VLTOTGER, s.CODFILIAL, s.VLDESCONTO, s.TIPOVENDA, s.OBS, s.TOTVOLUME, s.NUMITENS, s.CODCOB,
    s.NUMPED, s.CODPLPAG, s.CONDVENDA, s.UF, s.VLBASE, s.VLICMS, s.VLOUTRAS
  );

MERGE INTO WINTHOR.PCPEDCFV t
USING (
  SELECT 1 AS IMPORTADO, 7001 AS NUMPEDRCA, 1 AS CODUSUR, '12345678000199' AS CGCCLI, DATE '2026-04-20' AS DTABERTURAPEDPALM, DATE '2026-04-20' AS DTFECHAMENTOPEDPALM, 'PED-CLI-001' AS NUMPEDCLI, DATE '2026-04-21' AS DTENTREGA, '01' AS CODFILIAL, '001' AS CODCOB, 1 AS CODPLPAG, 1 AS CONDVENDA, DATE '2026-04-20' AS DTINCLUSAO, 5001 AS NUMPED, 1 AS CODCLI, 'A' AS POSICAO_ATUAL FROM dual
) s
ON (t.NUMPEDRCA = s.NUMPEDRCA)
WHEN MATCHED THEN UPDATE SET
  t.IMPORTADO = s.IMPORTADO,
  t.CODUSUR = s.CODUSUR,
  t.CGCCLI = s.CGCCLI,
  t.DTABERTURAPEDPALM = s.DTABERTURAPEDPALM,
  t.DTFECHAMENTOPEDPALM = s.DTFECHAMENTOPEDPALM,
  t.NUMPEDCLI = s.NUMPEDCLI,
  t.DTENTREGA = s.DTENTREGA,
  t.CODFILIAL = s.CODFILIAL,
  t.CODCOB = s.CODCOB,
  t.CODPLPAG = s.CODPLPAG,
  t.CONDVENDA = s.CONDVENDA,
  t.DTINCLUSAO = s.DTINCLUSAO,
  t.NUMPED = s.NUMPED,
  t.CODCLI = s.CODCLI,
  t.POSICAO_ATUAL = s.POSICAO_ATUAL
WHEN NOT MATCHED THEN
  INSERT (
    IMPORTADO, NUMPEDRCA, CODUSUR, CGCCLI, DTABERTURAPEDPALM, DTFECHAMENTOPEDPALM, NUMPEDCLI,
    DTENTREGA, CODFILIAL, CODCOB, CODPLPAG, CONDVENDA, DTINCLUSAO, NUMPED, CODCLI, POSICAO_ATUAL
  )
  VALUES (
    s.IMPORTADO, s.NUMPEDRCA, s.CODUSUR, s.CGCCLI, s.DTABERTURAPEDPALM, s.DTFECHAMENTOPEDPALM, s.NUMPEDCLI,
    s.DTENTREGA, s.CODFILIAL, s.CODCOB, s.CODPLPAG, s.CONDVENDA, s.DTINCLUSAO, s.NUMPED, s.CODCLI, s.POSICAO_ATUAL
  );

MERGE INTO WINTHOR.PCPEDIFV t
USING (
  SELECT 7001 AS NUMPEDRCA, '12345678000199' AS CGCCLI, 1 AS CODUSUR, DATE '2026-04-20' AS DTABERTURAPEDPALM, 1001 AS CODPROD, 2.000000 AS QT, 23.900000 AS PVENDA, 7891000000001 AS CODAUXILIAR, 1 AS NUMSEQ, DATE '2026-04-20' AS DTINCLUSAO, 'N' AS BONIFIC, 5001 AS NUMPED, 'PED-CLI-001' AS NUMPEDCLI, 1 AS NUMITEMPED, DATE '2026-04-21' AS DTENTREGA FROM dual
) s
ON (t.NUMPEDRCA = s.NUMPEDRCA AND t.NUMSEQ = s.NUMSEQ)
WHEN MATCHED THEN UPDATE SET
  t.CGCCLI = s.CGCCLI,
  t.CODUSUR = s.CODUSUR,
  t.DTABERTURAPEDPALM = s.DTABERTURAPEDPALM,
  t.CODPROD = s.CODPROD,
  t.QT = s.QT,
  t.PVENDA = s.PVENDA,
  t.CODAUXILIAR = s.CODAUXILIAR,
  t.DTINCLUSAO = s.DTINCLUSAO,
  t.BONIFIC = s.BONIFIC,
  t.NUMPED = s.NUMPED,
  t.NUMPEDCLI = s.NUMPEDCLI,
  t.NUMITEMPED = s.NUMITEMPED,
  t.DTENTREGA = s.DTENTREGA
WHEN NOT MATCHED THEN
  INSERT (
    NUMPEDRCA, CGCCLI, CODUSUR, DTABERTURAPEDPALM, CODPROD, QT, PVENDA, CODAUXILIAR,
    NUMSEQ, DTINCLUSAO, BONIFIC, NUMPED, NUMPEDCLI, NUMITEMPED, DTENTREGA
  )
  VALUES (
    s.NUMPEDRCA, s.CGCCLI, s.CODUSUR, s.DTABERTURAPEDPALM, s.CODPROD, s.QT, s.PVENDA, s.CODAUXILIAR,
    s.NUMSEQ, s.DTINCLUSAO, s.BONIFIC, s.NUMPED, s.NUMPEDCLI, s.NUMITEMPED, s.DTENTREGA
  );

MERGE INTO WINTHOR.PCSUGESTAOCOMPRAC t
USING (
  SELECT 8001 AS NUMSUGESTAO, 1 AS CODFORNEC, '01' AS CODFILIAL, 1 AS CODUSUARIOSUGESTAO, DATE '2026-04-20' AS DATASUGESTAO, 'C' AS TIPODESCARGA, 'N' AS IMPORTACAO, 'C' AS TIPOEMBALAGEMPEDIDO, DATE '2026-04-27' AS DTPREVENT FROM dual
) s
ON (t.NUMSUGESTAO = s.NUMSUGESTAO)
WHEN MATCHED THEN UPDATE SET
  t.CODFORNEC = s.CODFORNEC,
  t.CODFILIAL = s.CODFILIAL,
  t.CODUSUARIOSUGESTAO = s.CODUSUARIOSUGESTAO,
  t.DATASUGESTAO = s.DATASUGESTAO,
  t.TIPODESCARGA = s.TIPODESCARGA,
  t.IMPORTACAO = s.IMPORTACAO,
  t.TIPOEMBALAGEMPEDIDO = s.TIPOEMBALAGEMPEDIDO,
  t.DTPREVENT = s.DTPREVENT
WHEN NOT MATCHED THEN
  INSERT (NUMSUGESTAO, CODFORNEC, CODFILIAL, CODUSUARIOSUGESTAO, DATASUGESTAO, TIPODESCARGA, IMPORTACAO, TIPOEMBALAGEMPEDIDO, DTPREVENT)
  VALUES (s.NUMSUGESTAO, s.CODFORNEC, s.CODFILIAL, s.CODUSUARIOSUGESTAO, s.DATASUGESTAO, s.TIPODESCARGA, s.IMPORTACAO, s.TIPOEMBALAGEMPEDIDO, s.DTPREVENT);

MERGE INTO WINTHOR.PCSUGESTAOCOMPRAI t
USING (
  SELECT 8001 AS NUMSUGESTAO, 1001 AS CODPROD, 15.000000 AS QTSUGERIDA, 10.000000 AS QTPEDIDO, 6001 AS NUMPED, 'Compra sugerida automaticamente' AS OBS, 'A' AS STATUS, 1 AS CODUSUARIOPROCESSAMENTO, DATE '2026-04-20' AS DATAPROCESSAMENTO, 18.900000 AS PCOMPRALIQSUGERIDO, 5.0000 AS PERICM, 5.0000 AS PERCREDICMS, 5.0000 AS PERCICMSDIFERIDO, 5.000000 AS PESOLIQDI FROM dual
) s
ON (t.NUMSUGESTAO = s.NUMSUGESTAO AND t.CODPROD = s.CODPROD)
WHEN MATCHED THEN UPDATE SET
  t.QTSUGERIDA = s.QTSUGERIDA,
  t.QTPEDIDO = s.QTPEDIDO,
  t.NUMPED = s.NUMPED,
  t.OBS = s.OBS,
  t.STATUS = s.STATUS,
  t.CODUSUARIOPROCESSAMENTO = s.CODUSUARIOPROCESSAMENTO,
  t.DATAPROCESSAMENTO = s.DATAPROCESSAMENTO,
  t.PCOMPRALIQSUGERIDO = s.PCOMPRALIQSUGERIDO,
  t.PERICM = s.PERICM,
  t.PERCREDICMS = s.PERCREDICMS,
  t.PERCICMSDIFERIDO = s.PERCICMSDIFERIDO,
  t.PESOLIQDI = s.PESOLIQDI
WHEN NOT MATCHED THEN
  INSERT (
    NUMSUGESTAO, CODPROD, QTSUGERIDA, QTPEDIDO, NUMPED, OBS, STATUS,
    CODUSUARIOPROCESSAMENTO, DATAPROCESSAMENTO, PCOMPRALIQSUGERIDO, PERICM,
    PERCREDICMS, PERCICMSDIFERIDO, PESOLIQDI
  )
  VALUES (
    s.NUMSUGESTAO, s.CODPROD, s.QTSUGERIDA, s.QTPEDIDO, s.NUMPED, s.OBS, s.STATUS,
    s.CODUSUARIOPROCESSAMENTO, s.DATAPROCESSAMENTO, s.PCOMPRALIQSUGERIDO, s.PERICM,
    s.PERCREDICMS, s.PERCICMSDIFERIDO, s.PESOLIQDI
  );

MERGE INTO WINTHOR.PCESTCOM t
USING (
  SELECT 30001 AS NUMTRANSENT, 0.00 AS VLDEVOLUCAO, 12.50 AS VLESTORNO, DATE '2026-04-20' AS DTESTORNO, 1 AS CODUSUR, 1 AS CODFUNC, 40001 AS NUMTRANSVENDA, 'Estorno seed' AS HISTORICO, DATE '2026-04-20' AS DTLANC, 12.50 AS VLESTORNOCMV FROM dual
) s
ON (t.NUMTRANSENT = s.NUMTRANSENT)
WHEN MATCHED THEN UPDATE SET
  t.VLDEVOLUCAO = s.VLDEVOLUCAO,
  t.VLESTORNO = s.VLESTORNO,
  t.DTESTORNO = s.DTESTORNO,
  t.CODUSUR = s.CODUSUR,
  t.CODFUNC = s.CODFUNC,
  t.NUMTRANSVENDA = s.NUMTRANSVENDA,
  t.HISTORICO = s.HISTORICO,
  t.DTLANC = s.DTLANC,
  t.VLESTORNOCMV = s.VLESTORNOCMV
WHEN NOT MATCHED THEN
  INSERT (NUMTRANSENT, VLDEVOLUCAO, VLESTORNO, DTESTORNO, CODUSUR, CODFUNC, NUMTRANSVENDA, HISTORICO, DTLANC, VLESTORNOCMV)
  VALUES (s.NUMTRANSENT, s.VLDEVOLUCAO, s.VLESTORNO, s.DTESTORNO, s.CODUSUR, s.CODFUNC, s.NUMTRANSVENDA, s.HISTORICO, s.DTLANC, s.VLESTORNOCMV);

MERGE INTO WINTHOR.PCEMPR t
USING (
  SELECT 1 AS MATRICULA, 'Funcionario Seed' AS NOME, DATE '2026-01-10' AS ADMISSAO, 'Sao Paulo' AS CIDADE, 'SP' AS ESTADO, 'A' AS SITUACAO, '12345678901' AS CPF, 'T' AS TIPOVENDA, '01' AS CODFILIAL, 1 AS CODUSUR, 'funcionario.seed@empresa.local' AS EMAIL, 'M' AS SEXO, DATE '1990-01-01' AS DTNASC FROM dual
) s
ON (t.MATRICULA = s.MATRICULA)
WHEN MATCHED THEN UPDATE SET
  t.NOME = s.NOME,
  t.ADMISSAO = s.ADMISSAO,
  t.CIDADE = s.CIDADE,
  t.ESTADO = s.ESTADO,
  t.SITUACAO = s.SITUACAO,
  t.CPF = s.CPF,
  t.TIPOVENDA = s.TIPOVENDA,
  t.CODFILIAL = s.CODFILIAL,
  t.CODUSUR = s.CODUSUR,
  t.EMAIL = s.EMAIL,
  t.SEXO = s.SEXO,
  t.DTNASC = s.DTNASC
WHEN NOT MATCHED THEN
  INSERT (MATRICULA, NOME, ADMISSAO, CIDADE, ESTADO, SITUACAO, CPF, TIPOVENDA, CODFILIAL, CODUSUR, EMAIL, SEXO, DTNASC)
  VALUES (s.MATRICULA, s.NOME, s.ADMISSAO, s.CIDADE, s.ESTADO, s.SITUACAO, s.CPF, s.TIPOVENDA, s.CODFILIAL, s.CODUSUR, s.EMAIL, s.SEXO, s.DTNASC);

INSERT INTO WINTHOR.PCHISTEST (
  CODFILIAL, CODPROD, "DATA", QTEST, QTESTGER, CUSTOCONT, CUSTOREAL, CUSTOFIN,
  CUSTOREP, VLVENDA, DESCRICAO, UNIDADE, EMBALAGEM, HISTORICO
)
SELECT
  '01', 1001, DATE '2026-04-20', 120.00000000, 120.00000000, 19.500000, 19.500000, 19.500000,
  19.500000, 23.90, 'ARROZ TIPO 1 5KG', 'UN', 'FD', 'S'
FROM dual
WHERE NOT EXISTS (
  SELECT 1
  FROM WINTHOR.PCHISTEST h
  WHERE h.CODFILIAL = '01'
    AND h.CODPROD = 1001
    AND h."DATA" = DATE '2026-04-20'
);
