-- Seed isolada para cadastro de produtos.
-- Mantém a massa de 100 produtos e centraliza as tabelas:
-- PCPRODUT, PCEMBALAGEM, PCPRODFILIAL e PCPRODSIMIL.

BEGIN
  FOR i IN 1..100 LOOP
    MERGE INTO WINTHOR.PCPRODUT t
    USING (
      SELECT
        5000 + i AS CODPROD,
        'PRODUTO AVANCADO ' || LPAD(i, 3, '0') AS DESCRICAO,
        200 + MOD(i - 1, 25) + 1 AS CODEPTO,
        300 + MOD(i - 1, 25) + 1 AS CODSEC,
        ROUND(0.350 + (i * 0.071), 3) AS PESOBRUTO,
        ROUND(0.300 + (i * 0.066), 3) AS PESOLIQ,
        CASE MOD(i, 6)
          WHEN 0 THEN 24
          WHEN 1 THEN 1
          WHEN 2 THEN 6
          WHEN 3 THEN 12
          WHEN 4 THEN 18
          ELSE 20
        END AS QTUNITCX,
        CASE MOD(i, 4)
          WHEN 0 THEN 'CX'
          WHEN 1 THEN 'UN'
          WHEN 2 THEN 'PC'
          ELSE 'FD'
        END AS EMBALAGEM,
        ROUND(4.5 + (i * 0.83), 4) AS CUSTOREP
      FROM dual
    ) s
    ON (t.CODPROD = s.CODPROD)
    WHEN MATCHED THEN
      UPDATE SET
        t.DESCRICAO = s.DESCRICAO,
        t.CODEPTO = s.CODEPTO,
        t.CODSEC = s.CODSEC,
        t.PESOBRUTO = s.PESOBRUTO,
        t.PESOLIQ = s.PESOLIQ,
        t.QTUNITCX = s.QTUNITCX,
        t.EMBALAGEM = s.EMBALAGEM,
        t.CUSTOREP = s.CUSTOREP
    WHEN NOT MATCHED THEN
      INSERT (
        CODPROD, DESCRICAO, CODEPTO, CODSEC, PESOBRUTO, PESOLIQ, QTUNITCX, EMBALAGEM, CUSTOREP
      )
      VALUES (
        s.CODPROD, s.DESCRICAO, s.CODEPTO, s.CODSEC, s.PESOBRUTO, s.PESOLIQ, s.QTUNITCX, s.EMBALAGEM, s.CUSTOREP
      );
  END LOOP;
END;
/

BEGIN
  FOR i IN 1..100 LOOP
    MERGE INTO WINTHOR.PCTABPR t
    USING (
      SELECT
        5000 + i AS CODPROD,
        1 AS NUMREGIAO,
        ROUND(10.5 + MOD(i, 35) + (i * 0.11), 6) AS PTABELA,
        ROUND(9.9 + MOD(i, 33) + (i * 0.10), 6) AS PVENDA,
        ROUND(3 + MOD(i, 8), 2) AS PERDESCMAX,
        ROUND(12 + MOD(i, 16), 2) AS MARGEM,
        'N' AS EXCLUIDO,
        DATE '2026-04-20' - MOD(i, 15) AS DTULTALTPVENDA
      FROM dual
    ) s
    ON (t.CODPROD = s.CODPROD AND t.NUMREGIAO = s.NUMREGIAO)
    WHEN MATCHED THEN
      UPDATE SET
        t.PTABELA = s.PTABELA,
        t.PVENDA = s.PVENDA,
        t.PERDESCMAX = s.PERDESCMAX,
        t.MARGEM = s.MARGEM,
        t.EXCLUIDO = s.EXCLUIDO,
        t.DTULTALTPVENDA = s.DTULTALTPVENDA
    WHEN NOT MATCHED THEN
      INSERT (CODPROD, NUMREGIAO, PTABELA, PVENDA, PERDESCMAX, MARGEM, EXCLUIDO, DTULTALTPVENDA)
      VALUES (s.CODPROD, s.NUMREGIAO, s.PTABELA, s.PVENDA, s.PERDESCMAX, s.MARGEM, s.EXCLUIDO, s.DTULTALTPVENDA);
  END LOOP;
END;
/

BEGIN
  FOR filial_rec IN (
    SELECT DISTINCT TRIM(CODIGO) AS CODFILIAL
    FROM WINTHOR.PCFILIAL
    WHERE CODIGO IS NOT NULL
  ) LOOP
    FOR i IN 1..100 LOOP
      MERGE INTO WINTHOR.PCEMBALAGEM t
      USING (
        SELECT
          TO_NUMBER(filial_rec.CODFILIAL) * 1000000000000 + 5000 + i AS CODAUXILIAR,
          5000 + i AS CODPROD,
          CASE MOD(i, 4)
            WHEN 0 THEN 'CX'
            WHEN 1 THEN 'UN'
            WHEN 2 THEN 'PC'
            ELSE 'FD'
          END AS EMBALAGEM,
          'UN' AS UNIDADE,
          1 AS QTUNIT,
          ROUND(8.5 + (i * 0.95), 3) AS PTABELA,
          ROUND(7.9 + (i * 0.91), 3) AS PVENDA,
          DATE '2026-04-20' - MOD(i, 10) AS DTULTALTPTABELA,
          DATE '2026-04-20' - MOD(i, 8) AS DTULTALTPVENDA,
          100 + MOD(i - 1, 25) + 1 AS CODFUNCALTPTABELA,
          100 + MOD(i - 1, 25) + 1 AS CODFUNCALTPVENDA,
          100 + MOD(i, 50) AS QTMAXVENDA,
          ROUND(12 + MOD(i, 18), 2) AS MARGEM,
          30 + MOD(i, 120) AS PRAZOVAL,
          filial_rec.CODFILIAL AS CODFILIAL,
          'N' AS EXCLUIDO,
          'S' AS PERMITEMULTIPLICACAO,
          'S' AS USABALANCATOLEDO,
          ROUND(0.350 + (i * 0.071), 8) AS PESOBRUTO,
          ROUND(0.300 + (i * 0.066), 8) AS PESOLIQ,
          CASE MOD(i, 4)
            WHEN 0 THEN 24
            WHEN 1 THEN 1
            WHEN 2 THEN 6
            ELSE 12
          END AS QTMULTIPLA,
          ROUND(1.00000000, 8) AS FATORCONVERSAO,
          DATE '2026-04-20' - MOD(i, 15) AS DTCADASTRO
        FROM dual
      ) s
      ON (t.CODAUXILIAR = s.CODAUXILIAR AND t.CODPROD = s.CODPROD)
      WHEN MATCHED THEN
        UPDATE SET
          t.EMBALAGEM = s.EMBALAGEM,
          t.UNIDADE = s.UNIDADE,
          t.QTUNIT = s.QTUNIT,
          t.PTABELA = s.PTABELA,
          t.PVENDA = s.PVENDA,
          t.DTULTALTPTABELA = s.DTULTALTPTABELA,
          t.DTULTALTPVENDA = s.DTULTALTPVENDA,
          t.CODFUNCALTPTABELA = s.CODFUNCALTPTABELA,
          t.CODFUNCALTPVENDA = s.CODFUNCALTPVENDA,
          t.QTMAXVENDA = s.QTMAXVENDA,
          t.MARGEM = s.MARGEM,
          t.PRAZOVAL = s.PRAZOVAL,
          t.CODFILIAL = s.CODFILIAL,
          t.EXCLUIDO = s.EXCLUIDO,
          t.PERMITEMULTIPLICACAO = s.PERMITEMULTIPLICACAO,
          t.USABALANCATOLEDO = s.USABALANCATOLEDO,
          t.PESOBRUTO = s.PESOBRUTO,
          t.PESOLIQ = s.PESOLIQ,
          t.QTMULTIPLA = s.QTMULTIPLA,
          t.FATORCONVERSAO = s.FATORCONVERSAO,
          t.DTCADASTRO = s.DTCADASTRO
      WHEN NOT MATCHED THEN
        INSERT (
          CODAUXILIAR, CODPROD, EMBALAGEM, UNIDADE, QTUNIT, PTABELA, PVENDA,
          DTULTALTPTABELA, DTULTALTPVENDA, CODFUNCALTPTABELA, CODFUNCALTPVENDA,
          QTMAXVENDA, MARGEM, PRAZOVAL, CODFILIAL, EXCLUIDO, PERMITEMULTIPLICACAO,
          USABALANCATOLEDO, PESOBRUTO, PESOLIQ, QTMULTIPLA, FATORCONVERSAO, DTCADASTRO
        )
        VALUES (
          s.CODAUXILIAR, s.CODPROD, s.EMBALAGEM, s.UNIDADE, s.QTUNIT, s.PTABELA, s.PVENDA,
          s.DTULTALTPTABELA, s.DTULTALTPVENDA, s.CODFUNCALTPTABELA, s.CODFUNCALTPVENDA,
          s.QTMAXVENDA, s.MARGEM, s.PRAZOVAL, s.CODFILIAL, s.EXCLUIDO, s.PERMITEMULTIPLICACAO,
          s.USABALANCATOLEDO, s.PESOBRUTO, s.PESOLIQ, s.QTMULTIPLA, s.FATORCONVERSAO, s.DTCADASTRO
        );
    END LOOP;
  END LOOP;
END;
/

BEGIN
  FOR filial_rec IN (
    SELECT DISTINCT TRIM(CODIGO) AS CODFILIAL
    FROM WINTHOR.PCFILIAL
    WHERE CODIGO IS NOT NULL
  ) LOOP
    FOR i IN 1..100 LOOP
      MERGE INTO WINTHOR.PCPRODFILIAL t
      USING (
        SELECT
          5000 + i AS CODPROD,
          filial_rec.CODFILIAL AS CODFILIAL,
          100 + MOD(i - 1, 25) + 1 AS CODCOMPRADOR,
          'N' AS PROIBIDAVENDA,
          'N' AS FORALINHA,
          'S' AS REVENDA,
          20 + MOD(i, 30) AS ESTOQUEIDEAL,
          CASE MOD(i, 4)
            WHEN 0 THEN 24
            WHEN 1 THEN 1
            WHEN 2 THEN 6
            ELSE 12
          END AS MULTIPLO,
          'S' AS ATIVO,
          5 + MOD(i, 20) AS ESTOQUEMIN,
          120 + MOD(i * 3, 80) AS ESTOQUEMAX
        FROM dual
      ) s
      ON (t.CODPROD = s.CODPROD AND t.CODFILIAL = s.CODFILIAL)
      WHEN MATCHED THEN
        UPDATE SET
          t.CODCOMPRADOR = s.CODCOMPRADOR,
          t.PROIBIDAVENDA = s.PROIBIDAVENDA,
          t.FORALINHA = s.FORALINHA,
          t.REVENDA = s.REVENDA,
          t.ESTOQUEIDEAL = s.ESTOQUEIDEAL,
          t.MULTIPLO = s.MULTIPLO,
          t.ATIVO = s.ATIVO,
          t.ESTOQUEMIN = s.ESTOQUEMIN,
          t.ESTOQUEMAX = s.ESTOQUEMAX
      WHEN NOT MATCHED THEN
        INSERT (
          CODPROD, CODFILIAL, CODCOMPRADOR, PROIBIDAVENDA, FORALINHA, REVENDA,
          ESTOQUEIDEAL, MULTIPLO, ATIVO, ESTOQUEMIN, ESTOQUEMAX
        )
        VALUES (
          s.CODPROD, s.CODFILIAL, s.CODCOMPRADOR, s.PROIBIDAVENDA, s.FORALINHA, s.REVENDA,
          s.ESTOQUEIDEAL, s.MULTIPLO, s.ATIVO, s.ESTOQUEMIN, s.ESTOQUEMAX
        );
    END LOOP;
  END LOOP;
END;
/

BEGIN
  FOR i IN 1..15 LOOP
    MERGE INTO WINTHOR.PCPRODSIMIL t
    USING (
      SELECT
        5000 + i AS CODPROD,
        5000 + i + 1 AS CODSIMIL,
        100 + MOD(i - 1, 25) + 1 AS CODFUNCLANC,
        DATE '2026-04-20' - MOD(i, 12) AS DTLANC,
        CASE MOD(i, 2)
          WHEN 0 THEN 'V'
          ELSE 'A'
        END AS TIPOPROD,
        MOD(i - 1, 9) + 1 AS PRIORIDADE,
        CASE MOD(i, 3)
          WHEN 0 THEN 'T'
          WHEN 1 THEN 'S'
          ELSE 'A'
        END AS TIPOTROCA,
        'Produto similar isolado em seed propria' AS OBSERVACAO
      FROM dual
    ) s
    ON (t.CODPROD = s.CODPROD AND t.CODSIMIL = s.CODSIMIL)
    WHEN MATCHED THEN
      UPDATE SET
        t.CODFUNCLANC = s.CODFUNCLANC,
        t.DTLANC = s.DTLANC,
        t.TIPOPROD = s.TIPOPROD,
        t.PRIORIDADE = s.PRIORIDADE,
        t.TIPOTROCA = s.TIPOTROCA,
        t.OBSERVACAO = s.OBSERVACAO
    WHEN NOT MATCHED THEN
      INSERT (CODPROD, CODSIMIL, CODFUNCLANC, DTLANC, TIPOPROD, PRIORIDADE, TIPOTROCA, OBSERVACAO)
      VALUES (s.CODPROD, s.CODSIMIL, s.CODFUNCLANC, s.DTLANC, s.TIPOPROD, s.PRIORIDADE, s.TIPOTROCA, s.OBSERVACAO);
  END LOOP;
END;
/
